### ISSUE TITLE
could you add a parameter like -f that can specify a filename? 

### ISSUE THREAD

**Issue by cissusnar** [nst/objc_dep#18]
I want analyze a single file, but objc_dep only support analyze directory.

**Comment by jomnius** [comment]
Not sure what analysing only one file would give you, but a suggestion: create folder and copy that one file there. Then analyze the folder?

**Comment by cissusnar** [comment]
I want port some classes(files) to another xcode Target,  analysing one file(or some files) will very helpful for porting codes.
